baseURL = "https://slava02.github.io/santegidio-ru-recipes-from-monday/"
languageCode = "ru"
title = "Рецепты от группы понедельника"
theme = "recipe"
disableKinds = ["sitemap"]
pluralizeListTitles = false
paginate = 20
SectionPagesMenu = "main"

[outputs]
home = ["HTML"]
page = ["HTML"]

[taxonomies]
category = "categories"

[params]
paginateWindow = 3
featuredCount = 20

[markup.goldmark.renderer]
unsafe = true
